### ISSUE TITLE
Add Support for cli version 15.2.8

### ISSUE THREAD

**Issue by pavan612** [rushik1992/ngx-hierarchy#1]
Hi!
Update Support for higher versions of angular.

**Comment by pavan612** [comment]
Hi @rushik1992 any  update on this issue.

**Comment by rushik1992** [comment]
Hi Package is updated to Angular 19 @pavan612

**Comment by pavan2712** [comment]
Hi @rushik1992 can you update support for Angular 20.

**Comment by rushik1992** [comment]
@pavan2712 create new issue for that
